version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - API_PORT=${API_PORT:-3000}
      - API_HOST=${API_HOST:-0.0.0.0}
    expose:
      - "3000"
    networks:
      - ft_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile.combined
    ports:
      - "${PROXY_PORT:-443}:443"
      - "${HTTP_REDIRECT_PORT:-80}:80"
    depends_on:
      - api
    networks:
      - ft_network

networks:
  ft_network:
    driver: bridge